# Generated by Django 4.2.20 on 2025-05-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identification_document',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='identification_document_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
