# Generated by Django 4.2.20 on 2025-05-10 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafftype',
            name='deleted_status',
            field=models.BooleanField(default=False),
        ),
    ]
