# Generated by Django 4.2.20 on 2025-05-11 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_stafftype_deleted_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='id_number',
        ),
    ]
