# Generated by Django 4.2.20 on 2025-05-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_remove_staff_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
