# Generated by Django 4.2.20 on 2025-05-10 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffTypeAuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('action', models.CharField(max_length=255, unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_by', to=settings.AUTH_USER_MODEL)),
                ('staff_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_type', to='staff.stafftype')),
            ],
            options={
                'db_table': 'staff_type_audit_trail',
            },
        ),
    ]
