# Generated by Django 4.2.20 on 2025-05-12 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit_trail', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafftypeaudittrail',
            name='action_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stafftypeaudittrail',
            name='staff_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_type', to='staff.stafftype'),
        ),
        migrations.AddField(
            model_name='staffaudittrail',
            name='action_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_action_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffaudittrail',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='staff.staff'),
        ),
    ]
