# Generated by Django 4.2.20 on 2025-05-10 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_trail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stafftypeaudittrail',
            name='action',
            field=models.CharField(max_length=255),
        ),
    ]
