# Generated by Django 4.2.20 on 2025-05-10 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_trail', '0002_alter_stafftypeaudittrail_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafftypeaudittrail',
            name='deleted_status',
            field=models.BooleanField(default=False),
        ),
    ]
