# Generated by Django 4.2.20 on 2025-05-10 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit_trail', '0003_stafftypeaudittrail_deleted_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stafftypeaudittrail',
            name='deleted_status',
        ),
    ]
