# Generated by Django 4.2.20 on 2025-05-11 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_remove_staff_id_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit_trail', '0004_remove_stafftypeaudittrail_deleted_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('action', models.CharField(max_length=255)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_action_by', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='staff.staff')),
            ],
            options={
                'db_table': 'staff_audit_trail',
            },
        ),
    ]
